name: ğŸ› ï¸ Build Flutter Debug APK

# Global Environment Variables from your main workflow
-  on:
-    workflow_dispatch:

    steps:
      # --- SETUP ---

      - name: 1. â¬‡ï¸ Checkout Repository
        uses: actions/checkout@v4

            # --- DEPENDENCIES ---

      - name: 4. Get Flutter Dependencies
        run: flutter pub get

      # --- GENERATE DEBUG KEY ---

      - name: 5. ğŸ”‘ Generate Debug Keystore
        run: |
          keytool -genkey -v -keystore android/app/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
        shell: bash

      # --- BUILD ---

      - name: 6. ğŸ—ï¸ Build An APK
        run: flutter clean 

      - name: 6. ğŸ—ï¸ Build
        run: flutter build apk --debug

      # --- UPLOAD ARTIFACT ---

      - name: 7. ğŸ’¾ Upload Debug APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ethio_shop-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk # Standard debug APK output path
          retention-days: 7
